services:
  - type: web_service
    name: the-hive-card-game-backend
    env: node
    root: .
    buildCommand: npm --prefix packages/contracts install && npm --prefix packages/contracts run build && npm --prefix apps/backend install && npm --prefix apps/backend run build
    startCommand: npm --prefix apps/backend run start
    envVars:
      - key: PORT
        value: "3001"
      - key: CLIENT_ORIGIN
        value: "https://the-hive-card-game.onrender.com"

  - type: static_site
    name: the-hive-card-game
    env: node
    root: .
    buildCommand: npm --prefix packages/contracts install && npm --prefix packages/contracts run build && npm --prefix apps/frontend install && npm --prefix apps/frontend run build
    publishPath: apps/frontend/dist
    envVars:
      - key: VITE_SOCKET_URL
        value: "https://the-hive-card-game-backend.onrender.com"
